server:
  port: 8086

spring:
  datasource:
    url: jdbc:h2:mem:refunddb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.r2dbc: DEBUG


